# Generated by Django 3.1.5 on 2021-02-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virgool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(max_length=100),
        ),
    ]
